### ISSUE TITLE
Migrate away from nokogiri

### ISSUE THREAD

**Issue by AliSoftware** [NijiDigital/gyro#18]
gyro uses the `nokogiri` gem to do the XML parsing of the `xcdatamodel` file.

But `nokogiri` is known in the Ruby world to be hard to install (it's a compiled gem written in C, which gets compiled on your computer when you install it, and compilation can fail for multiple reasons).

So when things go right it's ok and a very fast parsing gem, but if the install generates errors upon compiling the gem it gets scary for the user (especially one not used to ruby) and hard to figure out what to do (at that point most people abort installation and don't try any further)

xcdatamodel files are not that huge to parse and don't really require a high-performance XML parser, so migrating away to a different gem which won't risk having install problems would be nice.

**Comment by StevenWatremez** [comment]
I found `[Oga](https://github.com/YorickPeterse/oga)`. I tried it with `gyro` and it's easy to implement cause of `xpath` usage is similar to `nokogiri`.

**Comment by AliSoftware** [comment]
I was more thinking about just using REXML which seems to be the lib of choice to do XML parsing in ruby after nokogiri, especially since REXML is included in most ruby distributions already, so that would mean one less dependency for gyro!

https://www.xml.com/pub/a/2005/11/09/rexml-processing-xml-in-ruby.html

**Comment by StevenWatremez** [comment]
Ah nice. I tried to implement `REXML` in this [branch](https://github.com/NijiDigital/gyro/tree/rexml). It works fine.
