### ISSUE TITLE
Folder Harmonisation

### ISSUE THREAD

**Issue by StevenWatremez** [NijiDigital/gyro#29]
There is a difference between `android` template folder name and `java` fixtures folder name. Questions are open to discuss about naming !

**Comment by AliSoftware** [comment]
I'd prefer `java` as:

1) For iOS we named them `swift` not `iOS`
2) In the future we'll probably have `kotlin`, so we have to disambiguate anyway

**Comment by AliSoftware** [comment]
Additional notes: in the `specs/fixtures/java` folder, we have `no_value` and `json` subfolders that have custom names not matching the `xcdatamodel` they are corresponding to (`relationship_type` and `json_key_path` respectively). I don't know why we did use a custom name here, we should probably rename them
