### ISSUE TITLE
Design a logo for this tool

### ISSUE THREAD

**Issue by AliSoftware** [NijiDigital/gyro#5]

**Comment by AliSoftware** [comment]
@jpsim @mrackwitz @TimOliver any idea if we'd be allowed to use a reference of the Realm logo as part of our own tool logo ?

Maybe like put it in the bottom right corner of our icon, or drawing some icon of a tool on top of the Realm logo or something, given that this tool is dedicated to generating Realm models?
What's the licence on the Realm logo?

Thx

**Comment by TimOliver** [comment]
Hey @AliSoftware! Thanks again for building this tool! This is really great!

Uhhh, that's actually a really good question! We hadn't really considered guidelines for usage of the logo by third party projects at this point.

Our main concern with that is we wouldn't want users to accidentally assume this is an official product and then come to @Realm with support requests (This has happened in the past with a certain Xcode Alcatraz plugin, so it's something in which we're quite wary!).

The marketing folks are going to have an internal discussion about this to see what they would think is best for this sort of case. We'll get back to you on this as soon as possible. :)

**Comment by AliSoftware** [comment]
Cool, thanks for your feedback!
I totally understand you wouldn't want people to think this is an official product you'd offer support for 😜

Note that we haven't thought about what our logo might look like yet, so this was a preventive question but still interested in case we decide to at least drop a reference 😉

**Comment by AliSoftware** [comment]
@TimOliver any news from your marketing folks? Thx :wink:

**Comment by TimOliver** [comment]
Ahh sorry @AliSoftware!

The last I heard, we're going to ask that third party developers to please don't use the Realm logo for unofficial libraries. I haven't heard from the marketing folks in a little while, but I would assume they're still considering the options on what we can do here.

For the time being, I'd recommend considering a logo that evokes the feeling of Realm (ie, it draws from the Realm logo colours), but doesn't directly use the circular logo.

Sorry I couldn't bring any better news!

**Comment by AliSoftware** [comment]
Fair enough, thanks for the feedback anyway!

**Comment by AliSoftware** [comment]
![logo](https://cloud.githubusercontent.com/assets/216089/24874920/8ed66058-1e26-11e7-837e-2af61a9fce2a.png)

Quickly designed logo now that we have the new name: (by a non-designer — me — so pardon the job quality 😄)

Do you think this kind of logo would be OK with Realm?

**Comment by jpsim** [comment]
I think that looks great! However, I've received feedback from our design team and there are a few modifications they'd like to see before this can receive their "blessing".

> Don’t modify the Realm logo or the wordmark in any way other than scaling. Do not alter the colors, waves, shapes, or aspect ratios. Do not add or subtract anything. Do not overlay/underlay anything.

So if the pink ring that overlays the logo was "tilted" a bit more as to not obstruct the logo behind it, that would comply with the "not overlaying" clause. Also, if the Realm logo had a small white border, that would address the "rod" that's underlayed. With these two changes and my interpretation of our internal brand guidelines, your logo would comply.

**Comment by AliSoftware** [comment]
Like this?
![gyro](https://cloud.githubusercontent.com/assets/216089/24887131/e6f79e36-1e59-11e7-83d0-2bb138ef8b88.png)

**Comment by jpsim** [comment]
That passes our internal branding guidelines, so as far as those requirements go, this is 👌 . Thanks for making those changes.

Personally, I think tightening the rings to be smaller and closer to the logo would make it feel a bit more "balanced", but now we're discussing design _taste_ rather than _requirements_.

**Comment by AliSoftware** [comment]
Thanks!
Purple ring brought closer, pink one stretched a little (as wide as before but pinched in height) and a little less weight overall… and that gives the new official logo, just added in the README:
![new logo](https://github.com/NijiDigital/gyro/blob/master/logo.png?raw=true)

Hope you like it 😉

**Comment by jpsim** [comment]
Looks great. 👍 💯
